### ISSUE TITLE
Incomplete Data Reporting

### ISSUE THREAD

**Issue by str245** [bergerx/kubectl-status#45] opened 2020-06-22 14:10 UTC
Hello, I checked the operation in **2 Clusters** type:

**Kubernetes:** v1.18.0
**OS:** Oracle Linux v7.8
**Kernel:** 4.1.12-124.26.5.el7uek.x86_64
**Conf:** IaC (_based on identical template in both cases_)

In one of the clusters it reports:

Node / worker1, created 13d ago
  linux Oracle Linux Server 7.8 (amd64), kernel 4.1.12-124.35.4.el7uek.x86_64, kubelet v1.18.2, kube-proxy v1.18.2
  cpu: 0.107 / 1 (**11%**) **<-**
  mem: 2.9GB / 7.1GB (**42%**) **<-**
  ephemeral-storage: 2.2GB
  images 50

**Values ​​of a node describe:**

Addresses:
  Hostname: worker1
Capacity:
  cpu: 2
  ephemeral-storage: 3030800Ki
  hugepages-2Mi: 0
  memory: 8155976Ki
  pods: 110
Allocatable:
  cpu: 1
  ephemeral-storage: 2256314364
  hugepages-2Mi: 0
  memory: 7005000Ki
  pods: 110

Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource Requests Limits
  -------- -------- ------
  cpu 550m (55%) 200m (20%)
  memory 562Mi (8%) 562Mi (8%)
  ephemeral-storage 0 (0%) 0 (0%)
  hugepages-2Mi 0 (0%) 0 (0%)

**And in the other Cluster reports:**

Node / worker2, created 14d ago
  linux Oracle Linux Server 7.8 (amd64), kernel 4.1.12-124.26.5.el7uek.x86_64, kubelet v1.18.2, kube-proxy v1.18.2
  cpu: 5, mem: 7.1GB, ephemeral-storage: 2.2GB **<--**
  images 50

**Values ​​of a node describe:**

Addresses:
  Hostname: worker2
Capacity:
  cpu: 6
  ephemeral-storage: 3030800Ki
  hugepages-2Mi: 0
  memory: 8156080Ki
  pods: 110
Allocatable:
  cpu: 5
  ephemeral-storage: 2256314364
  hugepages-2Mi: 0
  memory: 7005104Ki
  pods: 110

Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource Requests Limits
  -------- -------- ------
  cpu 1710m (34%) 2200m (44%)
  memory 2042Mi (29%) 450Mi (6%)
  ephemeral-storage 0 (0%) 0 (0%)
  hugepages-2Mi 0 (0%) 0 (0%)

In both cases, they are recent installations sharing versions and parameters with each other. I cannot understand the reason why in one it presents the CPU and Ram occupancy ratios correctly and in another case No.

**Comment by bergerx** [comment] 2021-09-29 00:25
I believe this was because of the existence of the [metrics-server](https://github.com/kubernetes-sigs/metrics-server) component. Major distributions have it deployed by default. But local dev environments don't have it deployed by default ( e.g. see https://github.com/kubernetes-sigs/kind/issues/398 and https://kubernetes.io/docs/tutorials/hello-minikube/#enable-addons)

The easiest way to check if you have it is to run `kubectl get nodemetrics` command. Check `kubectl get nodemetrics -o yaml`. if you are curious what's available in this resource, metrics-server is also used by `kubectl top` commands. you can also verify the same by running `kubectl top node`.

**Comment by bergerx** [comment] 2021-09-29 00:33
Duplicate of #165

**Closed by bergerx** 2021-09-29 00:33 UTC
